### PR TITLE
fix(dependencies): use url = 0.5; the bump to 1.0 broke us

### LINKED ISSUE #23: unresolved name `form_urlencoded::serialize` [E0425]
I'm trying to compile google-drive3, but the build stops building one of it's dependencies -- yup-oauth2 -- using rustc-1.8 on debian testing. Any idea what might be wrong?

    [cut1]/out/lib.rs:189:17: 189:43 error: unresolved name `form_urlencoded::serialize` [E0425]
    [cut1]/out/lib.rs:189                 form_urlencoded::serialize(&[("client_id", client_id),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:189:17: 189:43 help: run `rustc --explain E0425` to see a detailed explanation
    [cut1]/out/lib.rs:588:17: 588:43 error: unresolved name `form_urlencoded::serialize` [E0425]
    [cut1]/out/lib.rs:588                 form_urlencoded::serialize(&[("client_id", &self.id[..]),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:588:17: 588:43 help: run `rustc --explain E0425` to see a detailed explanation
    [cut1]/out/lib.rs:865:17: 865:43 error: unresolved name `form_urlencoded::serialize` [E0425]
    [cut1]/out/lib.rs:865                 form_urlencoded::serialize(&[("client_id", client_id),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:865:17: 865:43 help: run `rustc --explain E0425` to see a detailed explanation
    [cut1]/out/lib.rs:194:160: 194:164 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:194                 match self.client.borrow_mut().post(FlowType::Device.as_ref()).header(ContentType("application/x-www-form-urlencoded".parse().unwrap())).body(&*req).send()
                                                                                                                                                                                        ^~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:524:25: 524:58 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:524                         res.read_to_string(&mut json_str).unwrap();
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:594:151: 594:155 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:594                 match self.client.borrow_mut().post(GOOGLE_TOKEN_URL).header(ContentType("application/x-www-form-urlencoded".parse().unwrap())).body(&*req).send()
                                                                                                                                                                               ^~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:602:25: 602:58 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:602                         res.read_to_string(&mut json_str).unwrap();
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:593:17: 593:25 error: the trait `core::marker::Sized` is not implemented for the type `str` [E0277]
    [cut1]/out/lib.rs:593             let json_str =
                                          ^~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:593:17: 593:25 help: run `rustc --explain E0277` to see a detailed explanation
    [cut1]/out/lib.rs:593:17: 593:25 note: `str` does not have a constant size known at compile-time
    [cut1]/out/lib.rs:593:17: 593:25 note: all local variables must have a statically known size
    [cut1]/out/lib.rs:871:151: 871:155 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:871                 match self.client.borrow_mut().post(GOOGLE_TOKEN_URL).header(ContentType("application/x-www-form-urlencoded".parse().unwrap())).body(&*req).send()
                                                                                                                                                                               ^~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:879:25: 879:58 error: the type of this value must be known in this context
    [cut1]/out/lib.rs:879                         res.read_to_string(&mut json_str).unwrap();
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:870:17: 870:25 error: the trait `core::marker::Sized` is not implemented for the type `str` [E0277]
    [cut1]/out/lib.rs:870             let json_str =
                                          ^~~~~~~~
    [cut0]//src/lib.rs:71:1: 71:47 note: in this expansion of include!
    [cut1]/out/lib.rs:870:17: 870:25 help: run `rustc --explain E0277` to see a detailed explanation
    [cut1]/out/lib.rs:870:17: 870:25 note: `str` does not have a constant size known at compile-time
    [cut1]/out/lib.rs:870:17: 870:25 note: all local variables must have a statically known size

### PR DESCRIPTION
**Pull request by dermesser**
Fixes #23.

### CODE REVIEW

**Comment by dermesser** [comment]
...a proper upgrade to `url = 1.0` requires some more work, but this should be a good solution, too.

They changed `serialize()` to `byte_serialize()`: http://servo.github.io/rust-url/url/form_urlencoded/fn.byte_serialize.html

**Comment by bluss** [comment]
Note to the maintainer: All the open upper bound version requirements must be fixed, otherwise your crate will break from new major versions again.

**Comment by bluss** [comment]
The fix would be to use something like this:

```toml
[dependencies]
chrono = "0.2"
log = "0.3"
mime = "0.1"
url = "0.5"
hyper = "0.8.0"
itertools = "0.4"
...
```

This way only compatible upgrades from those versions will be used. This is the standard way to use version requirements.

**Comment by Byron** [comment]
Thank you ! I am now spending some time on getting this crate into a fully working state.

**Comment by bluss** [comment]
The other deps remain with open ended version ranges, so they can still result in breakage the same way at some point down the line.

**Comment by dermesser** [comment]
@bluss, you're right, I've been meaning to do this.

**Comment by bluss** [comment]
Great.

**Comment by dermesser** [comment]
(see #35)

**Pull request merged**
