### PR TITLE
Code reorganization in order to better support more flows

### PR DESCRIPTION
**Pull request by dermesser**
I found some of the modules having inconsistent or unfitting names, or being a sort of a grab bag.

Therefore -- sorry for this big change, but I think it simplifies finding things either me or users are looking for, as well as future extensions like the ServiceAccountFlow I'm working on :-)

The public interface is unchanged except for two new helper methods that users of the library used to have to implement themselves although they are the same for everyone.

### CODE REVIEW

**Comment by Byron** [comment]
Thank you so much for contributing once again!
Please excuse the delay, but I would like to take a moment to look at the code, but won't make it this weekend.
Thanks for your understanding.

**Comment by dermesser** [comment]
No worries, I think I still need to fix the build anyways :D

**Comment by dermesser** [comment]
nightly is broken, but at first glance it doesn't seem my fault.

**Comment by Byron** [comment]
Hi @dermesser , thanks a lot for the great work !
I hope you won't mind me adding you to the 'authors' variable, so you show up in [the authors field on crates.io](https://crates.io/crates/yup-oauth2). In case you do, I will of course revert the commit and re-publish.

**Comment by Byron** [comment]
@dermesser One questions remains: Does [this line](https://github.com/Byron/yup-oauth2/blob/83bfbab114c5b811044bfff0da00b0087de1a489/src/authenticator_delegate.rs#L140) work for you ? When I tried it by pasting the code into my terminal, it wouldn't detect the end of line and thus never proceed. What made it work for me is something like this : `echo <code-obtained-previously> | <google-cli>`. To my mind, this would be the last thing to get right before the CLIs are ready for general consumption.

**Comment by dermesser** [comment]
It *works on my machine* :) (aside from the fact that I deleted the client ID I'm using)

```
Please direct your browser to https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive.metadata.readonly&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=812031924520-3oiu1sr8m44ja90i3vqddl1tks95g9dh.apps.googleusercontent.com, follow the instructions and enter the code displayed here: 
abcdefg
Token retrieval failed with error: Token API error: deleted_client The OAuth client was deleted.
```

The binary I'm using has the following dependencies:

```
hyper = "^ 0.9.0"
google-drive3 = "0.1.15"
serde = "0.6.0"
serde_json = "0.6.0"
yup-oauth2 = "0.6.3"
```

and it doesn't do anything special. According to the documentation on `read_line`, that line should work, and most shells flush stdin to the process when Enter is pressed. Have you tried a different terminal? Or is the binary itself maybe hanging at some point after?

**Comment by Byron** [comment]
@dermesser Interestingly, I just tried it with the new example application (thanks :)), and it did indeed work ! Last time I tried it was with one of the google command-line tools (youtube, possibly). I will review that one, maybe the err is somewhere in my setup.

**Comment by Byron** [comment]
@dermesser Cannot reproduce - after all, all google-cli agents are now using the flow that basically does everything automatically. That works just fine and is totally awesome !

**Pull request merged**
